#+TITLE:  Zsh Themes
#+AUTHOR: Xavier Garrido
#+DATE:   2013-02-12
#+OPTIONS: toc:nil num:nil ^:nil

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:
This sould provides a set of themes for =zsh=
shell in a "literate way" through Org-mode files.

The latest version is at http://github.com/xgarrido/zsh-themes

* Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

There are different way to install this plugin :
** In your =~/.zshrc=
1) Download the script or clone this repository:
   #+BEGIN_SRC sh :tangle no
     git clone git://github.com/xgarrido/zsh-themes.git
   #+END_SRC
2) Source this script *at the end* of =~/.zshrc=:
   #+BEGIN_SRC sh :tangle no
     source /path/to/zsh-themes/zsh-themes.plugin.zsh
   #+END_SRC
3) Source =~/.zshrc= to take changes into account:
   #+BEGIN_SRC sh :tangle no
     source ~/.zshrc
   #+END_SRC
** With [[https://github.com/zsh-users/antigen][antigen]] (recommended way)
Add the following line into your =~/.zshrc= file:
#+BEGIN_SRC sh :tangle no
  antigen-bundle xgarrido/zsh-themes
#+END_SRC
If you want to use the =nemo= theme, then write :
#+BEGIN_SRC sh :tangle no
  antigen-theme xgarrido/zsh-themes nemo
#+END_SRC

* Implementation
:PROPERTIES:
:CUSTOM_ID: implementation
:END:

Besides the fact that [[http://orgmode.org/][org-mode]] is used, this plugin does not use the org-babel
tangling features and thus, does not assume that emacs is properly installed and
set. All the tangling stuff is done through a simple [[file:Makefile][Makefile]] and some [[http://www.gnu.org/software/sed/][sed]]
tricks. In this way, it can be used without emacs. The only needed knowledge
about org-mode is the code wrapping that *must* be done using proper code blocks
calls (see [[http://orgmode.org/manual/Structure-of-code-blocks.html#Structure-of-code-blocks][org babel documentation]]). Nevertheless, it is recommended to have a
look on org-mode features especially folding/unfolding abilities which make the
read and the navigation pretty easy.

* Themes
There is only one theme defined and set to work within different machine
environment:

- [[file:zsh-themes-nemo.org][nemo]] theme
